[project]
name = 'Charity-Evaluator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.charity-registry]
path = 'contracts/charity-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.donation-tracker_]
path = 'contracts/donation-tracker_.clar'
clarity_version = 2
epoch = 2.5

[contracts.donor-voting]
path = 'contracts/donor-voting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
